hw04 completed
MykhayloOdesa/goit-node.js-hw-01_06 pull request #11
Opened 2023-06-04 17:26 UTC by MykhayloOdesa

Зробити пагінацію для колекції контактів (GET /contacts?page=1&limit=20).
Зробити фільтрацію контактів по полю обраного (GET /contacts?favorite=true)

for these 2 additional tasks i didn't do testing but i guess it should be ok

all the rest testing in attached zip at learning platform

and please if you have time re-check at your postman for json errors messages instead of html markup

2023-06-04 18:35 UTC, KhYulian commented on controllers/authController.js
> +  const passwordCompared = await bcrypt.compare(password, user.password);
```suggestion
  const isPasswordCorrect= await bcrypt.compare(password, user.password);
```
 it would be a better name

2023-06-04 18:36 UTC, KhYulian commented on controllers/authController.js
> +  res.status(204).json();
it's better to return a message e.g. "Successful logout"

2023-06-04 18:37 UTC, KhYulian commented on controllers/authController.js
> +  }
You shouldn't perform such checks in the controllers. Rely on Joi validation only

2023-06-04 18:38 UTC, KhYulian commented on controllers/contactsController.js
> +  if (favorite && favorite === "true") {
```suggestion
  if (favorite === "true") {
```

2023-06-04 18:38 UTC, KhYulian commented on controllers/contactsController.js
> +  if (favorite && favorite === "false") {
```suggestion
  if (favorite === "false") {
```

if it's undefined it won't be equal to 'false' anyway

2023-06-04 18:39 UTC, KhYulian commented on middlewares/authenticate.js
> +    next(new HttpError(401));
```suggestion
   return next(new HttpError(401));
```

2023-06-04 18:39 UTC, KhYulian commented on middlewares/authenticate.js
> +      next(new HttpError(401, "Not authorized"));
```suggestion
    return  next(new HttpError(401, "Not authorized"));
```

2023-06-04 18:40 UTC, KhYulian commented on services/contactsService.js
if you decided to write all logic in the controllers you should delete this file. Or you can write logic related to database requests in the services

2023-06-04 18:41 UTC, KhYulian requested changes
fixes required

2023-06-04 18:48 UTC, MykhayloOdesa commented on controllers/authController.js
> +  }
i see it's performed in validateBody.js as i understand

2023-06-04 18:50 UTC, MykhayloOdesa commented on controllers/contactsController.js
> +  if (favorite && favorite === "true") {
i guess i wanted to compare another checkings but misprinted

2023-06-04 18:52 UTC, MykhayloOdesa commented on controllers/contactsController.js
> +  if (favorite && favorite === "false") {
if (!favorite) {
    filter.favorite = false;
  }
  
  and like this one?

2023-06-04 18:53 UTC, MykhayloOdesa commented on middlewares/authenticate.js
> +    next(new HttpError(401));
yes
forgot that's if statement and needs to be terminated if any error observed

2023-06-04 18:56 UTC, MykhayloOdesa commented
fixed!

2023-06-04 18:58 UTC, MykhayloOdesa commented on services/contactsService.js
i will delete it

2023-06-05 05:10 UTC, KhYulian commented on controllers/authController.js
> +  }
Yes, it is

2023-06-05 05:11 UTC, KhYulian commented on controllers/contactsController.js
> +  if (favorite && favorite === "false") {
No, it should be like this if (favorite === "false") {... 
Because query parameter is not required

2023-06-05 05:12 UTC, KhYulian approved these changes
Great job

2023-06-05 05:12 UTC, merged